# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.lintul3 <- function(crop, weather, soil, control) {
    .Call('_Rlintul_lintul3', PACKAGE = 'Rlintul', crop, weather, soil, control)
}

.lintul1 <- function(crop, weather, control) {
    .Call('_Rlintul_lintul1', PACKAGE = 'Rlintul', crop, weather, control)
}

.lintul2 <- function(crop, weather, soil, control) {
    .Call('_Rlintul_lintul2', PACKAGE = 'Rlintul', crop, weather, soil, control)
}

